name: Build Images

on:
  push:
    branches:
      - master
  workflow_dispatch:   # allows manual trigger

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push PHP Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/php:8.4-fpm-alpine3.22
          docker build --target base_php -t $IMAGE_NAME -f php.Dockerfile .
          docker push $IMAGE_NAME

  build-php-nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push PHP & Nginx Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/php_nginx:8.4-fpm-alpine3.22
          docker build --target php_nginx -t $IMAGE_NAME -f php_nginx.Dockerfile .
          docker push $IMAGE_NAME
